version: '3.8'
services:
  crazyair-mock:
    image: wiremock/wiremock:3.3.1
    container_name: crazyair-mock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/crazyair:/home/wiremock/mappings
      - ./wiremock/crazyair:/home/wiremock/__files
  toughjet-mock:
    image: wiremock/wiremock:3.3.1
    container_name: toughjet-mock
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/toughjet:/home/wiremock/mappings
      - ./wiremock/toughjet:/home/wiremock/__files
